#!/usr/bin/env sh
RED="\033[1;31m"
BLUE="\033[34m"
GREEN="\033[1;32m"

linter_exit_code=0
eslint_files=$(git diff --cached --diff-filter=d --name-only --line-prefix=`git rev-parse --show-toplevel`/ | grep '.js$\|.ts$\|.vue$')
stylelint_files=$(git diff --cached --diff-filter=d --name-only --line-prefix=`git rev-parse --show-toplevel`/ | grep '.css$\|.vue$')

echo "${BLUE}(pre-commit) Running linters..."
if [ "$eslint_files" ]
then
  eslint --fix $eslint_files
  linter_exit_code=$?
fi

if [ "$stylelint_files" ]
then
  stylelint --fix $stylelint_files
  linter_exit_code=$?
fi

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED}❌ (pre-commit) Please fix linting errors before committing!"
  exit 1
else
  echo "${GREEN}✔ (pre-commit) ESlint and Stylelint did not find any errors!"
  exit 0
fi