#!/usr/bin/env sh

echo "(pre-commit) Cleaning compiled files..."
npm run clean

echo "(pre-commit) Building backend..."
npm run build:backend

linter_exit_code=0

echo "(pre-commit) Running linters..."
npm run lintfix
linter_exit_code=$?

if [ $linter_exit_code -ne 0 ]
then
  echo "❌ (pre-commit) Please fix linting errors before committing!"
  exit 1
else
  echo "✔ (pre-commit) ESlint and Stylelint did not find any errors!"
  exit 0
fi