[build]
command = "npm run deploy:netlify"
# MarkBind outputs into docs/_site, so publish that
publish = "docs/_site"

[build.environment]
# Prevent Netlify from trying to init submodules
GIT_SUBMODULE_STRATEGY = "none"
