module.exports.PAGE_EJS = '<!DOCTYPE html>\n'
  + '<html>\n'
  + '<head>\n'
  + '    <meta charset="utf-8">\n'
  + '    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n'
  + '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
  + '    <title><%= title %></title>\n'
  + '    <link rel="stylesheet" href="<%- asset.bootstrap %>">\n'
  + '    <link rel="stylesheet" href="<%- asset.highlight %>">\n'
  + '    <link rel="stylesheet" href="<%- asset.markbind %>">\n'
  + '</head>\n'
  + '<body>\n'
  + '<div id="app" class="container-fluid">\n'
  + '    <%- content %>\n'
  + '</div>\n'
  + '</body>\n'
  + '<script src="<%- asset.vue %>"></script>\n'
  + '<script src="<%- asset.vueStrap %>"></script>\n'
  + '<script src="<%- asset.setup %>"></script>\n'
  + '</html>\n';

module.exports.SITE_JSON_DEFAULT = '{\n'
  + '  "baseUrl": "",\n'
  + '  "pages": [\n'
  + '    {\n'
  + '      "src": "index.md",\n'
  + '      "title": "Hello World"\n'
  + '    }\n'
  + '  ],\n'
  + '  "ignore": [\n'
  + '    "_markbind/logs/*",\n'
  + '    "_site/*",\n'
  + '    "*.json",\n'
  + '    "*.md"\n'
  + '  ],\n'
  + '  "deploy": {\n'
  + '    "message": "Site Update."\n'
  + '  }\n'
  + '}\n';

module.exports.INDEX_MD_DEFAULT = '# Hello world\nWelcome to your page generated with MarkBind.\n';

module.exports.USER_VARIABLES_DEFAULT = '<span id="example">\n'
  + 'To inject this HTML segment in your markbind files, use {{ example }} where you want to place it.\n'
  + 'More generally, surround the segment\'s id with double curly braces.\n'
  + '</span>';
