const path = require('path');
const fs = require('fs-extra');

const VueCompiler = require('vue-template-compiler');
const { renderToString } = require('vue-server-renderer').createRenderer();

let bundle = require('@markbind/core-web/dist/js/vueCommonAppFactory.min');

const createLocalVue = require('./createLocalVue');
const logger = require('../utils/logger');

const vueRenderEscapeChars = {
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&amp;': '&',
};

const pageEntries = {}; // hold the mapping of sourcePath to latest built pages (for hot-reload dev purposes)

/**
 * Compiles page into Vue Application to get the page render function and places
 * it into a script so that the browser can retrieve the page render function to
 * render the page during Vue mounting.
 *
 * This is to avoid the overhead of compiling the page into Vue application
 * on the client's browser (alleviates FOUC). It is also the pre-requisite to enable SSR.
 *
 * @param content Page content to be compiled into Vue app
 */
async function compileVuePageAndCreateScript(content, pageConfig, pageAsset) {
  // Compile Vue Page
  const compiledVuePage = VueCompiler.compileToFunctions(content);

  // Set up script content
  const outputContent = `
    var pageVueRenderFn = ${compiledVuePage.render};
    var pageVueStaticRenderFns = [${compiledVuePage.staticRenderFns}];
  `;

  // Get script file name
  const pageHtmlFileName = path.basename(pageConfig.resultPath, '.html');
  const scriptFileName = `${pageHtmlFileName}.page-vue-render.js`;

  /*
   * Add the script file path for this page's render function to the page's assets (to populate page.njk).
   * The script file path is the same as the page's file path.
   */
  pageAsset.pageVueRenderJs = scriptFileName;

  // Get script's absolute file path to output script file
  const dirName = path.dirname(pageConfig.resultPath);
  const filePath = path.join(dirName, scriptFileName);

  await fs.outputFile(filePath, outputContent);

  return compiledVuePage;
}

/**
 * Renders Vue page app into html string (Vue SSR).
 * This function will install the MarkBindVue plugin and render the built Vue page content into html string.
 */
async function renderVuePage(compiledVuePage) {
  const { MarkBindVue, appFactory } = bundle;

  /*
   * Each installation of plugin pollutes the global scope of Vue.
   * Thus, we use a fresh copy of Vue each time we install MarkBindVue to prevent the global pollution.
   * This prevents the old plugin from affecting the new plugin installation (in development mode).
   */
  const LocalVue = createLocalVue();
  LocalVue.use(MarkBindVue);

  const VueAppPage = new LocalVue({
    render(createElement) {
      return compiledVuePage.render.call(this, createElement);
    },
    staticRenderFns: compiledVuePage.staticRenderFns,
    ...appFactory(),
  });

  let renderedContent = await renderToString(VueAppPage);

  /*
   * https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/basic.js
   *
   * vue-server-renderer automatically escapes various characters during rendering for security reasons.
   * We un-escape these characters as there shouldn't be any security concerns in our use-case.
   *
   * We only un-escape & and " for now so that the script redirect for userGuide/devGuide will work.
   * Un-escaping < and/or > will lead to hydration issues so we do not do it for now.
   */
  renderedContent = renderedContent.replace(/&(quot|amp);/g, match => vueRenderEscapeChars[match]);

  return renderedContent;
}

/**
 * Referenced from stackOverflow:
 * https://stackoverflow.com/questions/17581830/load-node-js-module-from-string-in-memory
 *
 * Credits to Dominic
 */
function requireFromString(src, filename) {
  const m = new module.constructor();
  m.paths = module.paths; // without this, we won't be able to require Vue in the string module
  m._compile(src, filename);
  return m.exports;
}

/**
 * Retrieves the latest updated MarkBindVue bundle from webpack compiler watcher,
 * re-render all the built pages, and output the page html files.
 * This function will only be used in development mode (for MarkBindVue bundle hot-reloading purposes).
 */
async function updateMarkBindVueBundle(newBundle) {
  logger.info(`Changes detected in MarkBind Vue Source Files: 
Bundle is regenerated by webpack and built pages are re-rendered with the latest bundle.`);

  // reassign the latest updated MarkBindVue bundle
  bundle = requireFromString(newBundle, '');

  Object.values(pageEntries).forEach(async (pageEntry) => {
    const { page, compiledVuePage, pageNav } = pageEntry;
    const renderedVuePageContent = await renderVuePage(compiledVuePage);
    page.outputPageHtml(renderedVuePageContent, pageNav);
  });
}

const pageVueServerRenderer = {
  compileVuePageAndCreateScript,
  renderVuePage,
  updateMarkBindVueBundle,
  pageEntries,
};

module.exports = {
  pageVueServerRenderer,
};
