name: Bug Report
description: File a bug report
labels: ["c.Bug 🐛"]
body:
- type: dropdown
  id: existing
  attributes:
    label: Please confirm that you have searched existing issues in the repo
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - 'Yes, I have searched the existing issues'
      - 'No'
  validations:
    required: true
- type: input
  id: related
  attributes:
    label: Any related issues?
    description: |
      Are there existing issues that relate to this new issue? (Either covering other aspects/angles of the problem or providing context)
      e.g. #1, #2
  validations:
    required: false
- type: input
  id: environment
  attributes:
    label: Tell us about your environment
    description: The operating system that the project is running on etc
    placeholder: e.g. Windows 10
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: MarkBind version
    description: Which version of MarkBind?
    placeholder: e.g. 3.1.1
  validations:
    required: true
- type: textarea
  id: Description
  attributes:
    label:  Describe the bug and the steps to reproduce it
    description: |
      Please include the following, if availble:
      - actual, raw output
      - source code causing the issue
        - you are encouraged (though not required) to submit a PR that reproduces this in `packages/cli/test/functional/test_site/bugs/index.md`.
  
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label:  Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false