name: Feature request
description:  Suggest a new idea/feature for MarkBind
labels: ["c.Feature 🚀"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the request.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: related
  attributes:
    label: Any related issues?
    description: |
      Are there existing issues that relate to this new issue? (Either covering other aspects/angles of the feature or providing context)
      e.g. #1, #2
  validations:
    required: false
- type: dropdown
  id: aspect
  attributes:
    label: What is the area that this feature belongs to?
    description: Choose all related aspect(s)
    multiple: true
    options:
      - Author Usability
      - Reader Usability
      - CLI
      - Code Quality
      - DevOps
      - Documentation
      - Performance
      - Plugins
      - Security
      - Syntax
      - Testing
      - Other
  validations:
    required: false
- type: textarea
  id: request
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is.
    placeholder: e.g. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: alternates
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  id: extra
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
