name: E2E
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g npm@8.3.1
      - run: npm run setup
      - run: cd packages/cli
      - name: Run end-to-end tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 8
          max_attempts: 3
          retry_on: error
          command: npm run test:e2e
